lib/active_decorator/railtie.rb
When `ActionMailer::Base` is delivered by Model or Worker(like ActiveJob) method,
`ActiveDecorator::ViewContext.current` is `nil` and I cannot use view helper methods in decorator.
the reason is that `ActionMailer::Base` inherits `AbstractController::Base`,
but only ActionController::Base set view_context.
It becomes the problem mainly when I use `ActionMailer::Base#deliver_later` with active_decorator.
=> Add ViewContext::Filter include to ActionMailer::Base

spec/controllers/fake_detection_spec.rb
Hi, just fixed the next rspec deprecation message.
DEPRECATION: `expect { }.not_to raise_error(SpecificErrorClass)` is deprecated. Use `expect { }.not_to raise_error` (with no args) instead. 
Please see the discussion below for details.
https://github.com/rspec/rspec-expectations/issues/231
=> Fix rspec deprecation

lib/generators/rspec/templates/decorator_spec.rb
generator of rspec did not support existing rails_helper.rb from RSpec3, I coped.
=> supported rails_helper.rb

lib/active_decorator/decorator.rb, spec/fake_app/books/index.html.erb, spec/fake_app/fake_app.rb, spec/features/controller_ivar_spec.rb
`Array === <an instance of CollectionProxy>` returns `false` on at least AR-3.2.13.
I wonder why `obj.is_a?(Array)` was changed on 9abf6bb.
=> Fix AR::CollectionProxy is not decorated.

README.md, lib/active_decorator.rb, lib/active_decorator/config.rb, lib/active_decorator/decorator.rb, spec/model/configure_spec.rb
I have to be able to set decorator name suffix.
(This is a matter that has been talk on Asakusa.rb meetup.)
We can use the 'FooPresenter' instead of 'FooDecorator'.
```
ActiveDecorator::Config.configuration do |config|
config.decorator_suffix = 'Presenter'
end
```
=> configurable Decorator Name Suffix

lib/active_decorator/decorator.rb, spec/fake_app/fake_app.rb, spec/features/controller_ivar_spec.rb
Consider the case that a object which will decorate implements Proxy pattern, inherits the BasicObject and is using method_missing.
When proxy destination object is `ActiveRecord::Relation` like [Octopus::RelationProxy](https://github.com/tchandy/octopus/blob/master/lib/octopus/relation_proxy.rb) of [Octopus](https://github.com/tchandy/octopus), `alias_method_chain :to_a, :decorator` in `ActiveDecorator::Decorator#decorate` raises following error.
```
NameError:
undefined method `to_a' for class `Octopus::RelationProxy'
```
This is due to that confirmation of the object (`obj.is_a?(ActiveRecord::Relation)`) is executed on the proxy destination object, but alias operation of the method (`alias_method_chain: to_a,: decorator`) is executed in the singleton class of obj. The singleton class …
=> Use class_eval not singleton class when decorating ActiveRecord::Relation object

.travis.yml
=> Drop test for Ruby 1.8 & 1.9

spec/features/controller_ivar_spec.rb, spec/features/jbuilder_spec.rb, spec/features/partial_spec.rb, spec/spec_helper.rb
We `delete_all` all models in "spec_helper.rb"'s before block.
=> Remove duplicated `delete_all`

lib/active_decorator/decorator.rb
The delegation method is changed from `to_a` to `records` since Rails
5.0.0.beta3.
https://github.com/rails/rails/pull/23794
It's still in beta, so it chould change more until the release date :trollface:
=> Fix patch target in Rails 5.0.0.beta3

lib/active_decorator/helpers.rb, test/fake_app/app/views/books/errata.html.erb, test/fake_app/fake_app.rb, test/features/name_error_handling_test.rb
This fixes issue #70 by ensuring a ```NameError``` (wrapped in ```ActionView::Template::Error``` by rails) is properly raised when a ```NameError``` occurs in a decorator method.
=> Ensure NameError in decorator is properly handled

lib/active_decorator/decorator.rb, spec/lib/decorator_spec.rb
When decorate is called for an object that is already decorated nil is returned. Returning the object itself is more normal behavior.
=> Still return object when it is already decorated

README.md, lib/active_decorator/decorated.rb, lib/active_decorator/decorator.rb, lib/active_decorator/monkey/active_record/associations.rb, lib/active_decorator/railtie.rb, test/fake_app/app/views/authors/show.html.erb, test/fake_app/app/views/movies/show.html.erb, test/fake_app/fake_app.rb, test/features/association_test.rb
Decorate associations(`ActiveRecord::Associations::Association#target`) when `ActiveRecord::Associations::Association#owner` has passed through `ActiveDecorator::Decorator#decorate`.
`owner` is decorated by current logic, so with this change, associated objects come to be decorated in view context.
=> Decorate associated objects

lib/active_decorator/monkey/active_record/associations.rb, lib/active_decorator/railtie.rb, test/fake_app/app/views/authors/show.html.erb, test/fake_app/fake_app.rb, test/features/association_test.rb
In Rails 5.1, `ActiveRecord::Associations::CollectionAssociation#find_nth_or_last` is removed ([ref](https://github.com/rails/rails/commit/592e6b7e894e0fff07ab8233fce4bf77968ee8b6#diff-20f545c453ee24942b6f7ae565e9e369L645)), so decorating associations will be broken.
I fix it by monkey-patching to `ActiveRecord::Associations::CollectionProxy`.
=> Fix decorates associations for Rails 5.1 or higher

lib/generators/rspec/templates/decorator_spec.rb, lib/generators/test_unit/templates/decorator_test.rb
* `rails g decorator A::B` generates A::BDecorator, but the corresponding test/spec file
tries to refer it as BDecorator
* Such model names are commin if you use model from a Rails Engine
=> Fix generated tests for models with nested module

gemfiles/Gemfile-rails.5.1.x
Rails 5.1.0.rc2 has been released.
http://weblog.rubyonrails.org/2017/4/21/Rails-5-1-rc2
=> CI against Rails 5.1.0.rc2

lib/active_decorator/helpers.rb
I have seen that ActiveDecorator's raises NoMethodError for methods which absolutely exist; this is because it handles all the NoMethoderror and NameError raised in irrelevant classes on decorators. It makes debugging harder.
With this PR, AD re-raises errors if they are irrelevant to (and thus not be responsible to) the gem.
=> re-raise irrelevant errors which are not responsible to the gem

lib/active_decorator/decorator.rb, test/decorator_test.rb
Hi, I started using active_decorator, it's great!
but, I find bug.
When we decorate ActiveRecord::Relation which already decorated,  `ActiveDecorator::Decorator#decorate` returns `nil`.
So, I fix, if ActiveRecord::Relation is already decorated, `ActiveDecorator::Decorator#decorate` returns object.
=> Fix ActiveRecord::Relation which decorated return nil when `decorate` is called

lib/generators/rspec/templates/decorator_spec.rb
`RSpec.describe` works regardless of settings while `describe` alone lead can result in 
`undefined method 'describe' for main:Object` when tests are run.
https://github.com/rspec/rspec-rails/commit/ca0d249858903949052e06884e8e7f9d596cdc79
https://github.com/rspec/rspec-rails/issues/1048#issuecomment-44609422
=> Update decorator_spec.rb syntax

lib/generators/rails/USAGE, lib/generators/rails/decorator_generator.rb, lib/generators/rspec/decorator_generator.rb, lib/generators/test_unit/decorator_generator.rb, lib/generators/test_unit/templates/decorator_test.rb
I found namespace problem in generator for TestUnit:
```bash
$ bin/rails g decorator user
$ bin/rails g decorator admin/user
```
```ruby
require 'test_helper'
class UserDecoratorTest < ActiveSupport::TestCase
def setup
@user = User.new.extend UserDecorator
end
end
require 'test_helper'
class UserDecoratorTest < ActiveSupport::TestCase # it does not have namespace :(
def setup
@user = Admin::User.new.extend Admin::UserDecorator
end
end
```
```ruby
require 'test_helper'
class UserDecoratorTest < ActiveSupport::TestCase
def setup
@user = User.new.extend UserDecorator
end
end
require 'test_helper'
class Admin::UserDecoratorTest < ActiveSupport::TestCase # namespaced class :D
def setup
@user = Admin::User.new.extend Admin::UserDecorator
end
end
```
And I've refactored with cosme:
- Separeted …
=> Fix generator for TestUnit

lib/active_decorator/railtie.rb
- The `:action_controller_api` hook is only included in Rails 5.2+.
- Adds support for using active_decorator without JBuilder.
@amatsuda Sorry for the mess with the previous pull request, I accidentally deleted my fork 🙇. Thanks for releasing a new version!
Fixes #95
=> Improve ActionController::API support.

lib/active_decorator/decorator.rb, test/decorator_test.rb
This is a feature request. Recently I came across a situation where I needed to `group_by` ActiveRecord::Relation in Controller action and pass it to view, only to fail to use its decorator methods. So I added another condition for decorating objects in Hash values. I reckon that it would be more friendly if active_decorator dug into Hash values recursively to check if there are any ActiveRecord models / ActiveRecord::Relation inside them.
Here is a sample code: https://github.com/FumiyaShibusawa/active-decorator-hash-sample
To sum it up, in Controller, Article instances would be grouped by its month.
```ruby
class ArticlesController < ApplicationController
def index
@articles = Article.where(published_at: Time.current..Date::Infinity.new)
.order(published_at: :asc)
.group_by { |a| …
```
=> Decorate objects in hash

lib/active_decorator/decorator.rb, test/decorator_test.rb, test/fake_app/app/decorators/comic_decorator.rb, test/fake_app/fake_app.rb
ActiveDecorator decorates incorrectly for the nested class that do not define decorator.
```ruby
comic = Foo::Comic.new
ActiveDecorator::Decorator.instance.decorate(comic)
comic.is_a?(ComicDecorator)  #=> true
```
If `Foo::ComicDecorator` is not defined, it should not use `ComicDecorator` instead of `Foo::ComicDecorator`.
The cause of the problem is 73dcdd67ae146ee9e76b1da9ae9e9dbd55529193, so we will revert it.
=> Fix wrong decoration for nested classes

lib/active_decorator/monkey/action_controller/base/rescue_from.rb
Hi there.
I have a issue that a error shows up when I run request rspecs that target controllers inherit ActionController::API and this Rails app uses ActiveDecorator.
Probably this is related #102 .
Plz confirm it.
https://gist.github.com/kamillle/15b575a0b6f12583e28bc102202fe288
```
NameError: undefined local variable or method `view_context' for #<TestController:0x00007fd232cc0f40>
Did you mean?  view_runtime> with backtrace:
```
```rb
class TestsController < ActionController:API
rescue_from Exception do |e|
head :internal_server_error
end
def new
raise
end
end
RSpec.describe TestsContoller, type: :request do
describe '#new' do
subject { get :new_test_url }
it do
is_expected.to have_http_status :internal_server_error
end
end
end
```
=> Fix a bug occurs when request spec targets contollers inherited AC::API

lib/active_decorator/helpers.rb
This pull request fixes Ruby 2.7 keyword arguments warning.
Currently active_decorator displays keyword arguments warning on a view context method calling with keyword arguments.
For example
```ruby
user.decorate.t('key.of.translation', value: 'foo')
```
```
/path/to/active_decorator-1.3.2/lib/active_decorator/helpers.rb:14: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/path/to/actionview-6.0.3.2/lib/action_view/helpers/translation_helper.rb:60: warning: The called method `t' is defined here
```
Use `ruby2_keywords` method to suppress the warnings.
Note that `def method_missing(method, *args, **kwargs, &block)` doesn't work on Ruby 2.6.
Because `Object#send` has different behaviors between Ruby 2.6 and 2.7.
```ruby
def m(*args) …
```
=> Fix Ruby 2.7 keyword arguments warning

.travis.yml, gemfiles/Gemfile-rails.6.1.x, lib/active_decorator/monkey/action_view/collection_renderer.rb, lib/active_decorator/monkey/action_view/object_renderer.rb, lib/active_decorator/monkey/action_view/partial_renderer.rb, lib/active_decorator/railtie.rb, test/fake_app/app/views/authors/_author.html.erb, test/fake_app/app/views/authors/_author_locals.html.erb, test/fake_app/app/views/authors/index.html.erb, test/fake_app/fake_app.rb, test/features/partial_test.rb
`PartialRenderer` was refactored by rails/rails#38594 This fixes to follow to new render behavior.
Also, updated tests for `partial`. Because objects of original tests were decorated via `RelationDecorator#records` and didn't affected by `PartialRenderer` monkey.
=> Support Rails 6.1

lib/active_decorator/decorator.rb, test/decorator_test.rb, test/fake_app/fake_app.rb
A model may implement or delegate `nil?` to check the value of an attribute rather than the object instance as a whole.
Action Text implemented `nil?` in this way and as a result decorating a model which has Action Text rich-text fields where those fields have empty contents will cause problems accessing the associated `ActionText::RichText` record after decoration.
e.g. https://github.com/rails/rails/blob/da5b1c3bb7041af03d5c24bce2639349f7fcb5c2/actiontext/app/models/action_text/rich_text.rb#L12
=> Decorate models where nil? returns true
